### ISSUE TITLE
App Crashes when push notification success in php script

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/GCM-ANE#10]
Hello,

I am using this GCM Ane with facebook ane of myflash lab, Everything is working fine on my android app, When i sent message from php script it give me result  as following

{"multicast_id":6046668513444897145,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1458025792967853%ae89ef00f9fd7ecd"}]}

Which means message was sent successfully, but instead of receiving message, my android app got crash, I am not getting what is wrong there, I am also pasting here my manifest 

My app id here is "air.com.fashionfista.fashion"

<manifestAdditions>
      <![CDATA[<manifest android:installLocation="auto">
		<uses-permission android:name="android.permission.INTERNET"/>
		<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
		<uses-permission android:name="android.permission.WAKE_LOCK"/>
		<uses-permission android:name="com.android.vending.BILLING"/>
		
		
		<uses-permission android:name="android.permission.GET_ACCOUNTS" />
		<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
		<permission android:name="air.com.fashionfista.fashion.permission.C2D_MESSAGE" android:protectionLevel="signature" />
		<uses-permission android:name="air.com.fashionfista.fashion.permission.C2D_MESSAGE" />
	
		
		<uses-permission android:name="android.permission.VIBRATE" />
		<application android:hardwareAccelerated="true" android:allowBackup="true" android:enabled="true">
			<activity android:hardwareAccelerated="false">
				<intent-filter>
					<action android:name="android.intent.action.MAIN" />
					<category android:name="android.intent.category.LAUNCHER" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.BROWSABLE" />
					<category android:name="android.intent.category.DEFAULT" />
					<data android:scheme="air.com.doitflash.exfacebook2" />
				</intent-filter>							
			</activity>
			<receiver android:name="com.fashionfista.fashion.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
				<intent-filter>
					<action android:name="com.google.android.c2dm.intent.RECEIVE" />
					<category android:name="air.com.fashionfista.fashion" />
				</intent-filter>
			</receiver>
			<service android:name="com.fashionfista.fashion.handler.GcmMessageHandler" />
				
			
			<activity android:name="com.fashionfista.fashion.alarm.WakeActivity" android:theme="@style/Theme.Transparent" />
			
			<activity android:name="com.facebook.FacebookActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.NoDisplay" />
			<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@style/Theme.Transparent" />
			
			<provider android:authorities="com.facebook.app.FacebookContentProvider000000000000000" android:name="com.facebook.FacebookContentProvider" android:exported="true" />
			<activity android:name="com.doitflash.facebook.sharing.MyShare" android:theme="@style/Theme.Transparent" />
			
			<activity android:name="com.doitflash.facebook.invite.MyInvite" android:theme="@style/Theme.Transparent" />
			<activity android:name="com.pozirk.payment.BillingActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:background="#30000000" />
		</application>
</manifest>]]>
    </manifestAdditions>

**Comment by navdeepyadav** [comment]
Will it be answered soon by support team, I am waiting for their reply, Or do i need to look for something other

**Comment by myflashlab** [comment]
*NOTICE: You need to join the club if you need direct email support*

Regarding your question, there are a lot of mistakes you need to fix in your project! Please study the documentations carefully first where we have explained all the necessary settings. If you have more questions, please feel free to ask.

**Comment by navdeepyadav** [comment]
I am using this ane with another myflashlab product facebook, If you still thinks that there are still bugs in it can you please provide me manifest settings with the facebook ane and push notification together

**Comment by navdeepyadav** [comment]
Your replies are not up to point and not helpful, i am really sorry to say but for this i am moving to milkman, that is much easier to apply and they are always available for support
