### ISSUE TITLE
App crashed when receive notification

### ISSUE THREAD

**Issue by amirgolshan** [myflashlab/GCM-ANE#11]
Hi!
I have downloaded the sample and used the ANE for as3 android application in adobe cs 6.
I've created a senderId with related API key and also i could get my phone's RegID with your sample application.
But the problem is that After sending GCM(http://www.myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/demoV4/) the application closed and crashed.
(I use air for android 20.0.0.204 and i manually add all manifest information exactly like the sample you prepared with my application package name)
What should i do to fix that.
Best.

**Comment by myflashlab** [comment]
When GCM arrives and the app crashes, it means that you are sending the GCM correctly but the app cannot receive it successfully and that happens mainly because something is wrong in the manifest. please recheck your manifest .xml file or post it here for us to have a look and possibly find the problem.

**Comment by amirgolshan** [comment]
Thank you for the response.
The xml file is as below:

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/20.0">
  <id>com.idea.push</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>test</filename>
  <description/>

  <name>test</name>

  <copyright/>
  <initialWindow>
    <content>test.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions>
      <![CDATA[<manifest android:installLocation="auto">
   <uses-permission android:name="android.permission.INTERNET"/>
     <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
        <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
        <permission android:name="air.com.idea.push.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
        <uses-permission android:name="air.com.idea.push.permission.C2D_MESSAGE"/>
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
      <uses-permission android:name="android.permission.WAKE_LOCK"/>
      <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
      <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
        <uses-permission android:name="com.android.alarm.permission.SET_ALARM"/>

        <uses-permission android:name="android.permission.VIBRATE"/>
       <application>
            <activity>
                <intent-filter>
                    <action android:name="android.intent.action.MAIN"/>
                    <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
                <intent-filter>
                    <action android:name="android.intent.action.VIEW"/>
                    <category android:name="android.intent.category.BROWSABLE"/>
                    <category android:name="android.intent.category.DEFAULT"/>
                    <data android:scheme="air.com.idea.push"/>
                </intent-filter>
            </activity>

            <receiver android:name="com.idea.push.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
                <intent-filter>
                    <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                    <category android:name="air.com.idea.push"/>
                </intent-filter>
            </receiver>
            <service android:name="com.idea.push.handler.GcmMessageHandler"/>
            <receiver android:name="com.idea.push.alarm.alarmTypes.Alarm_Notification"/>

            <receiver android:name="com.idea.push.alarm.RebootAutoStartAlarms">
                <intent-filter>
                    <action android:name="android.intent.action.BOOT_COMPLETED"/>
                </intent-filter>
            </receiver>

            <activity android:name="com.idea.push.alarm.WakeActivity" android:theme="@style/Theme.Transparent"/>
        </application>
</manifest>]]>
    </manifestAdditions>
  </android>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.gcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
  </extensions>
</application>

**Comment by myflashlab** [comment]
Please try to modify your message so we are able to see the complete information. right now, the message seems broken!

Anyway, even in your last post, I could quickly spot the problem. You have renamed the classes from the Java side of the extension too! please note that you must rename only the package name from the sample to your own application package name. for example. you are right to rename ```<data android:scheme="air.com.doitflash.gcm" />``` to ```<data android:scheme="air.com.idea.push"/>```

BUT you shouldn't have renamed ```<service android:name="com.idea.push.handler.GcmMessageHandler"/>``` for example! that's a mistake.

As a general rule, you should rename only those names which start with ```air.``` at the beginning. Please make sure to study the documents and the demo files more carefully while considering the above hints. https://github.com/myflashlab/GCM-ANE and you will have the GCM messages arrived to your app in no time. cheers.

**Comment by amirgolshan** [comment]
Thank you so much for the response.
The ane worked great for me using your advise.
But after receiving the notification no badge number appears over application icon.
How can i add this possibility to my application to show and increment the badge number over the application icon?
Best.

**Comment by myflashlab** [comment]
Glad to see the problem is solved. About the badges, I must say that Android does not support badges over icons at all!

**Comment by amirgolshan** [comment]
Thank you for your reply.But I think it may possible.I have some application installed on my phone with badget support when receiving any notification.Like "Telegram". You can check it and guide me if there is a solution.
Anyway Thank you so much for your great support.
Best.

**Comment by myflashlab** [comment]
There is still no official global Android API for badges for Android but different device providers have implemented their own API... read this post to learn more about this: http://stackoverflow.com/questions/20216806/how-to-add-a-notification-badge-count-to-application-icon-on-sony-xperia-devices

**Comment by amirgolshan** [comment]
Thank you for your answer and useful link.Best.
