### ISSUE TITLE
android is not showing the notification

### ISSUE THREAD

**Issue by tieblumer** [myflashlab/GCM-ANE#13]
Hello,

I'm trying this ane on Flash CC and it seems to be working correctly. 
When I send a notification from my server, it is being received by the app when it is running.
But he android notifications center does not display the notification on the tray, when the app is closed. 

I think it must have something to do with not finding an icon to display. I've tried different combinations of name and folder, when compiling the app and also when sending the message from the server, but with no luck.

Is there a special place to save the icons or a right way to call them from the server?

I may be wrong supposing it is an icon issue, but any way this is how I have my message configured on the server. By the way, I'm using node-gcm there. 

notification: {
			body: "This is a notification that will be displayed ASAP.",
			title: "Hello World",
			icon: "myicon"
		}

Thank you.

**Comment by myflashlab** [comment]
Not finding the icon is not the reason for not receiving a GCM. yet, please check out these links:

1) [to learn more about how to set the sound and icons for the GCM.](https://github.com/myflashlab/GCM-ANE/issues/2#issuecomment-179787546)

2) [to get GCM when app is in background or closed.](https://github.com/myflashlab/GCM-ANE/issues/6)

**Comment by tieblumer** [comment]
Still could not see the notification on the tray in any case. 
Thank you any way.

**Comment by myflashlab** [comment]
Is there anything else we could help you with? I think there must be a very small mistake in your setting that might be causing it but the above two links should have covered it. If you can have a look back, it might help. Thanks.

**Comment by tieblumer** [comment]
I have tried a different approach, with local push notifications, and it did work for what I need right now. 
But I'll try to resume the tests with myflashlab in the future and post here more information.

Thank you!
