### ISSUE TITLE
Playing custom sounds on Android notification

### ISSUE THREAD

**Issue by cowlinb6** [myflashlab/GCM-ANE#17]
Is it possible for the notifications on Android to play a custom sound?
In the demo payload I can see the following parameter
`"{"params":["sound01.mp3"],"name":"setSound"}`
however I can't seem to get this to work. I've tried various different paths to an audio file located inside my app, but nothing seems to get the audio to play.  Any ideas?

**Comment by myflashlab** [comment]
you probably will find this post very helpful https://github.com/myflashlab/GCM-ANE/issues/2#issuecomment-179787546
