### ISSUE TITLE
Manifest File Crazy

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/GCM-ANE#18]
I see you used "com.doitflash.gcm" but in one place I need to change, don't other
Why do you use same name for internal uses and demo? - it is crazy

Try to use for demo app - "com.domain.app" or other but not same with internal uses
I see facebook Manifest 
```

intent-filter
         .....
	data android:scheme="air.com.doitflash.exfacebook2" 
intent-filter
```

Do I change to my app ID or stay this scheme?
In GCM I need to change, in FB?

If you fix it you save time for support.
Or write new with out same ID
Or http://www.myflashlabs.com/adobe-air-gcm-tutorial-manifest-setup/ change where will be "com.domain.app"

Thanks and Sorry, It makes me crazzy

**Comment by myflashlab** [comment]
Sorry for the confusion, but actually there is an easy rule for that. Every package name that starts with ```air.``` should be changed to your own package name. others, should stay as they are.
