### ISSUE TITLE
Registration ID arrived, but notification does not appear.

### ISSUE THREAD

**Issue by Plozzer** [myflashlab/GCM-ANE#2]
We bought this ane and we would like to use it with flash professional on android, but we encountered an issue.

When we send the messagge from php, we have a page like:
http://www.myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/demoV4/ (we copied the php code on our server

we fill registration id received in GcmEvent.REGISTERED event and google server api key.
The registration id looks like: cE3GhzysX80:APA91bE7p4UfgtbB_vGaQOGKlq7a2CDwhSenB6G_IXKhuYEwlVRiuC_qyVo06rBQo47CazTJQFMo9z5gA-k-ZE_HDOMFR0rayHDfzaNM42qDPG778b4ql59KXshU1FGDzXPaegeqKi_1

We receive this response:

Google reply: {"multicast_id":5249950836319859627,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}

And no notification is received from our android device. (no GcmEvent.MESSAGE and no notification in android status bar)

Accordcing to ane documentation we use the following code inside an .as class:

package aaa.bbb
{
      ...
      import com.myflashlab.air.extensions.gcm.Gcm;
      import com.myflashlab.air.extensions.gcm.GcmEvent;
      ...

       public class GCMNotifications extends EventDispatcher 
	{
		private var ANDROID_SENDER_ID:String="XXXXXXXXXX";
                var _ex:Gcm = new Gcm(ANDROID_SENDER_ID, null);

		public  function Init(...)
		{
			_ex.addEventListener(GcmEvent.REGISTERED, onRegIdReceived);
			_ex.addEventListener(GcmEvent.UNREGISTERED, onUnregistered);
			_ex.addEventListener(GcmEvent.ERROR, onError);
			_ex.addEventListener(GcmEvent.MESSAGE, onMessage);	
			trace("regId = " + _ex.getRegId); 
			_ex.register();
		}
		
		private function onError(e:GcmEvent):void
		{
			trace("onError: ", e.param);
		}

		private function onRegIdReceived(e:GcmEvent):void
		{
			trace("onRegIdReceived" + e.param+ "  " +_ex.getRegId);
        	}

		private function onUnregistered(e:GcmEvent):void
		{
			trace("onUnregistered: ", e.param);
		}

		private function onMessage(e:GcmEvent):void
		{
			trace("onMessage: ", e.param);
		}

We think the invoke part does not matter with this issue and we don't report it.

The xml related to android manifest is:
&#60;manifestAdditions&#62;
&#60;manifest&#62;
&#60;uses-permission android:name="android.permission.INTERNET"/&#62;
&#60;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/&#62;
&#60;uses-permission android:name="android.permission.CAMERA"/&#62;
&#60;uses-permission android:name="android.permission.RECORD_AUDIO"/&#62;
&#60;uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/&#62;
&#60;uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/&#62;
&#60;uses-permission android:name="android.permission.GET_ACCOUNTS" /&#62;
&#60;uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" /&#62;

&#60;permission android:name="air.&#60;APPID&#62;.permission.C2D_MESSAGE" android:protectionLevel="signature" /&#62;
&#60;uses-permission android:name="air.&#60;APPID&#62;.permission.C2D_MESSAGE" /&#62;
&#60;uses-permission android:name="android.permission.WAKE_LOCK" /&#62;
&#60;uses-permission android:name="android.permission.VIBRATE" /&#62;
&#60;uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" /&#62;
&#60;uses-permission android:name="com.android.alarm.permission.SET_ALARM" /&#62;

&#60;activity&#62;
    &#60;intent-filter&#62;
        &#60;action android:name="android.intent.action.MAIN" /&#62;
        &#60;category android:name="android.intent.category.LAUNCHER" /&#62;
    &#60;/intent-filter&#62;
    &#60;intent-filter&#62;
        &#60;action android:name="android.intent.action.VIEW" /&#62;
        &#60;category android:name="android.intent.category.BROWSABLE" /&#62;
        &#60;category android:name="android.intent.category.DEFAULT" /&#62;
        &#60;data android:scheme=air.&#60;APPID&#62;." /&#62;
    &#60;/intent-filter&#62;
&#60;/activity&#62;

&#60;receiver android:name="com.doitflash.gcm.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" &#62;
    &#60;intent-filter&#62;
        &#60;action android:name="com.google.android.c2dm.intent.RECEIVE" /&#62;
        &#60;category android:name="air.&#60;APPID&#62;." /&#62;
    &#60;/intent-filter&#62;
&#60;/receiver&#62;

&#60;service android:name="com.doitflash.gcm.handler.GcmMessageHandler" /&#62;

&#60;receiver android:name="com.doitflash.gcm.alarm.alarmTypes.Alarm_Notification" /&#62;

&#60;receiver android:name="com.doitflash.gcm.alarm.RebootAutoStartAlarms"&#62;
    &#60;intent-filter&#62;
        &#60;action android:name="android.intent.action.BOOT_COMPLETED" /&#62;
    &#60;/intent-filter&#62;
&#60;/receiver&#62;
&#60;activity android:name="com.doitflash.gcm.alarm.WakeActivity" android:theme="@style/Theme.Transparent" /&#62;
&#60;/manifest&#62;
&#60;/manifestAdditions&#62;

we include these extensions:

<extensions>
    <extensionID>com.doitflash.air.extensions.dependency</extensionID>
    <extensionID>com.myflashlab.air.extensions.gcm</extensionID>
  </extensions>

and we include both gcm.ane and gcm,swf from the zip package. 
We tested on android 5.5.1 and AIR sdk 18.0.0.199 for Android.

Thank you in advice for your help!
Regards
Andrea

**Comment by myflashlab** [comment]
The first thing I noticed is your php response which says:

```Google reply: {"multicast_id":5249950836319859627,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]}```

as you see, Google reply is saying that it has not been able to send the gcm message in the first place. so it's no wonder you are not receiving it in your app.

Please make sure all the API keys you have entered are set correctly?

**Comment by myflashlab** [comment]
And by the way, please study the markup language here on GitHub here https://guides.github.com/features/mastering-markdown/ to know how to copy codes in your question so it will be readable. Thanks.

**Comment by Plozzer** [comment]
Thank you for fast reply, i update the message to make visible the xml code.
I followed the steps to obtain api key.

**Google Cloud Messaging for Android** is enabled on google developer console.

In credentials tab i have a ** Server API Key** that i use to send the notifications.

The project number on google developer console  is the **ANDROID_SENDER_ID** in the as code.

I noted the Server API key seems not related to Cloud messenging, but **it's generic for any google API, i'm not sure if this is correct**.

Also in Server API Key panels i left void the option **"Accept requests from these server IP addresses "**

Thank you
Andrea

**Comment by myflashlab** [comment]
@Plozzer well, all seems fine as you described it. but there is something going wrong on your server or the console for as long as Google gcm reply indicates an error.

try regenerating your server api key. (yes, you're right, that key is used for all server api keys and gcm is one of them)

when regenerating the server key, make it notlimited to a special ip address. (do this first to make sure the connection is established correctly first. then you can always limit it)

and then, also make sure your app is generating the regId based on a correct Android Sender ID.

**Comment by Plozzer** [comment]
Hi,
i was recreating the project, in the creation steps i found this page:
https://support.google.com/cloud/answer/6158862?hl=en#creating-android-api-keys
This step does not appear in your tutorial:
http://www.myflashlabs.com/adobe-air-gcm-tutorial-senderid-server-api-key-android/
Are you sure i don't have to add package name and fingerprint to create the api key?

**Comment by myflashlab** [comment]
Although Google has changed the console look a bit, the steps are still pretty much the same. here are some new screenshots which you may find helpful.

![01](http://myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/01.png)
![02](http://myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/02.png)
![03](http://myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/03.png)
![04](http://myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/04.png)

> I recreated project ad api key on google console and the first time i send the message,
Google reply: {"multicast_id":6701775391499419005,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1453288898422899%66e660e2f9fd7ecd"}]}

This is weird! and if Google replied ok on the first try, then maybe you have a mistake on your Android manifest setup. you may find this link helpful http://stackoverflow.com/questions/26718115/gcm-error-not-registered

**Comment by Plozzer** [comment]
Thank you so much, problem was the issue in stackoverflow in the manifest,
Now it works and i receive the notification message in the app, but i can't see the notification message in the android status bar when the app is in background or closed.

**Comment by myflashlab** [comment]
good :) you are at least one step closer. I think you will be able to fix the other problem by reading this tutorial more carefully. http://www.myflashlabs.com/adobe-air-gcm-tutorial-manifest-setup/

If you are sure that you have set the manifest all correctly. I suggest you to install Android Studio so you can use its debugging console. just let Android Studio open while your device is connected to your computer. then open the ADB log console and watch your device's log messages. then while you are  watching the logs and your app is closed, send a GCM... if there's an error in your manifest, you should see something related to that in the logs. that will probably tell you what is wrong in the manifest.

**Comment by Plozzer** [comment]
Hi,
i checked the manifest but i still have this issue. On android top bar there is no notification when app is in background or closed.

I tried logcat when app is closed and when app is opened, but i can't see differences.

CASE APP IN BACKGROUND
D/SensorService(  932): [SO] -0.265 0.095 9.630
I/GCM     ( 1665): GCM message air.eu.joyweb.colfarmademo 0:1454497339223924%66e
660e2f9fd7ecd
D/ActivityManager(  932): retrieveServiceLocked(): component = air.<myapp>/com.doitflash.gcm.handler.GcmMessageHandler; callingUser = 0; userId(t
arget) = 0


CASE APP IN FOREGROUD
D/SensorService(  914): [SO] -0.196 0.060 9.638
I/GCM     ( 1647): GCM message air.<myapp> 0:1454498987524983%66e
660e2f9fd7ecd
D/ActivityManager(  914): retrieveServiceLocked(): component = air<myapp>/com.doitflash.gcm.handler.GcmMessageHandler; callingUser = 0; userId(t
arget) = 0

I didn't add any custom icon or other resource for the notification, in the documentation link i see we could add custom icons or sound for the notification, where do we have to put these files?

Thank you in advance
Andrea

**Comment by myflashlab** [comment]
The Json you are putting together on the Android side is using this structure: https://github.com/myflashlab/alarmManager-ANE/

for example for setting the large icon, you have this setting in json:

```json
{

    "params":[
        0
    ],
    "name":"setLargeIconRes"

},
{

    "params":[
        "",
        128
    ],
    "name":"setLargeIcon"

},
{

    "params":[
        "icon_512.png",
        128
    ],
    "name":"setLargeIconSDcard"

}
```

to know exactly what parameters you should put there, you can compare them with the folloiwng:

```actionscript
alarmTask.setLargeIconRes(0x01080029); // to use large icons from assets OR sdcard, you must send 0 for setLargeIconRes param
//alarmTask.setLargeIconAssets("notificationIcons/icon_512.png"); // to use large icons from sdcard pass an empty string "" for setLargeIconAssets
//alarmTask.setLargeIconSDcard(File.documentsDirectory.resolvePath("icon_512.png"));
```

let's compare ```setLargeIconSDcard``` for example. in json we have ```"icon_512.png"``` and in the alarm manager settings we have ```File.documentsDirectory.resolvePath("icon_512.png")```

This means, that your icon is placed on the root of your device directory in ```File.documentsDirectory```

if you wish to put it somehwere else like 
```actionscript
File.documentsDirectory.resolvePath("my_folder/icon_512.png")
```
then you should enter the following in your gcm json
```json
    "params":[
        "my_folder/icon_512.png",
        128
    ],
    "name":"setLargeIconSDcard"
```

The same story goes for the notification sound.

**Comment by myflashlab** [comment]
about the gcm not being received when your app is closed, it should be related to your manifest settings. can you send us a demo apk? where we can copy the regId from it and test it locally?

**Comment by Plozzer** [comment]
I have the demo, how can i send it to you?

**Comment by myflashlab** [comment]
maybe just zip the demo and just attach it here?

**Comment by Plozzer** [comment]
it won't attach, maybe zip is too big.

**Comment by myflashlab** [comment]
Oh, well, you can try dropbox or Google docs to upload your content there and send the link here for us to download?

**Comment by Plozzer** [comment]
https://dl.dropboxusercontent.com/u/103113304/App/demopushandroid.zip

let ke know when you have it, then i ll delete the file.
you can use you php demo to send notifications.

**Comment by myflashlab** [comment]
yes, got it. we will check it a.s.a.p

**Comment by Plozzer** [comment]
thank you

**Comment by cowlinb6** [comment]
I'm also experiencing a similar issue to this, but only when I package my app using the production provisioning profile. I've had it working fine on iOS using the development profile, but when I use the production one the GCM server first returns as success message (though no notification appears) and then all subsequent requests return with the NotRegistered error.

I'm wondering if the registration token is being generated for the sandbox environment - are there any configuration options for this?

**Comment by myflashlab** [comment]
@Plozzer we just ran the demo apk but how can we copy the regID? if you could set the text field selectable, that would have been great so we could copy the String from there. it's not possible to distingush the small letter "l" from capital "I" :)

@cowlinb6 you should make sure your adHoc or release provisions/.p12 files are also set just similar to how you did it on the development steps.

**Comment by Plozzer** [comment]
This is new demo with text field on top with regid.
https://dl.dropboxusercontent.com/u/103113304/App/demopushandroid2.zip
Thank you

**Comment by myflashlab** [comment]
@Plozzer If you need to delete, you can do that. I downloaded the file. we will test this apk and let you know as soon as possible.

**Comment by Plozzer** [comment]
thank you

**Comment by cowlinb6** [comment]
As far as I can tell all my certificates and provisioning profiles are set correctly.  I've tried regenerating them and I still have the same issue. Is there anything else that needs changing between dev/production other than compiling with the different provisioning profile and changing the aps-environment setting?

I have seen reference to similar issues if the `kGGLInstanceIDAPNSServerTypeSandboxOption` is not set correctly. Is this handled by the ANE?

**Comment by myflashlab** [comment]
@cowlinb6 That property was stripped out in the last set of updates in some tries to automate it. anyway please update yourself with V4.9.3 and set the sandbox property to false when building for production.

```actionscript
Gcm.isSandbox = false;
```

let me know how it goes.

**Comment by myflashlab** [comment]
@Plozzer alright, I was able to extract the regId but we also need you server API key before we can test it. for security reasons please send the server api key to this email: (help at myflashlabs . com) and do link to this page to they know they should forward me the message. Thanks.

```json
Google reply: {"multicast_id":6119146745399244146,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}
```

**Comment by cowlinb6** [comment]
Looks like the new version has sorted it, thank you!

**Comment by Plozzer** [comment]
ok, we sent you the api key by email

**Comment by myflashlab** [comment]
Dear @Plozzer we just ran your apk and used your Server API key you sent through email and the gcm notification is delivered!!! when app is running and when app is closed.

I'm not sure why do you suggest it's not being delivered. it's working absolutely fine on the demo .apk you sent.

If you need more technical support, please drop us an email.

**Comment by Plozzer** [comment]
does it work when app is in background? The issue we have is when app is in background and the notification does not appear on the android notification bar.
We checked on 2 android devices and we cannot see the notification in the notification bar when app is in background.

**Comment by menicon** [comment]
Hi, How can I play a default SMS ringtone, instead of customise ringtone for the notification sound?
