### ISSUE TITLE
Android notification click doesn't open the app

### ISSUE THREAD

**Issue by Humi171421** [myflashlab/GCM-ANE#3]
Hello gentlemen,

we recently purchased your ANE GCM Extension but have run into a small problem: Push notifications works fine to Android and IOS devices, but on Android it won’t open the app when one presses the notification.

I worked through and adhered to your guide completely: http://www.myflashlabs.com/adobe-air-gcm-tutorial-manifest-setup/
App ID: de.betterbits.pushtest

At the bottom is an excerpt from Android manifest:

What am I missing? Any tips you can give me would be greatly appreciated!

Regards,
Andi Kaufmann

`<manifest android:installLocation="auto">
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
	<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
	<uses-permission android:name="android.permission.WAKE_LOCK"/>

	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<permission android:name="air.de.betterbits.pushtest.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="air.de.betterbits.pushtest.permission.C2D_MESSAGE" />

	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
	<uses-permission android:name="com.android.alarm.permission.SET_ALARM" />
	<uses-permission android:name="android.permission.VIBRATE"/>

	<category android:name="de.betterbits.pushtest" />

	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.CAMERA"/>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
	<uses-feature android:name="android.hardware.camera" android:required="false"/>
	<uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
	 
	<application>   
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.de.betterbits.pushtest" />
			</intent-filter>
		</activity>

		<receiver android:name="com.doitflash.gcm.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<category android:name="air.de.betterbits.pushtest" />
			</intent-filter>
		</receiver>
		<service android:name="com.doitflash.gcm.handler.GcmMessageHandler" />
		<receiver android:name="com.doitflash.gcm.alarm.alarmTypes.Alarm_Notification" />

		<receiver android:name="com.doitflash.gcm.alarm.RebootAutoStartAlarms">
			<intent-filter>
				<action android:name="android.intent.action.BOOT_COMPLETED" />
			</intent-filter>
		</receiver>

		<activity android:name="com.doitflash.gcm.alarm.WakeActivity" android:theme="@style/Theme.Transparent" />
	</application>
</manifest>`

**Comment by myflashlab** [comment]
your manifest setup seems all ok! although I don't know why you have ```<category android:name="de.betterbits.pushtest" />``` there. That's shouldn't be a problem though.

Please send us ADB log so we can see what error message you receive. (you can simply install Android Studio and open the ADB window and watch the logs as soon as you are hitting on the notification)

yet, a wild guess s that you are using FlashBuilder, right? if so, you should be careful with FB changing your app package name when in debug mode. watch these videos we have recorded: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by Humi171421** [comment]
Yes your wild guess was right. I'm using FlashBuilder and I got exactly the problem mentiond in the video. FlashBuilder set at the end of my AppID a ".debug". Now without the ".debug" everthing is working fine.

For other use that are stumbleing over this problem. If you start your app in debug mode, FlashBuilder will set a ".debug" at the end of your AppID. Here are some infos about, how do you change it in FlashBuilder 4.6 and 4.7

https://forums.adobe.com/thread/1044982?tstart=0

I would like to say thanks for your help :-)
