### ISSUE TITLE
App crashes upon receiving notification from PHP CURL (Android)

### ISSUE THREAD

**Issue by gtechman** [myflashlab/GCM-ANE#34]
Hello,

I have been unable to figure the issue out for over a week now. My Manifest as far as I can tell is error free. Could it be possible that the app is crashing because of the JSON variables in the string? I have posted my manifest just to make sure I don't have an issue there.

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/20.0">
    <id>com.futurelinesystems.filterwatch</id>
    <versionNumber>1.0.0</versionNumber>
    <filename>FilterWatch</filename>
    <description></description>
    
    <name>FilterWatch</name>
    
    <copyright></copyright>
    <initialWindow>
        <content>FW_Maintenance_man.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>false</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>cpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image96x96>AppIconsForPublish/FilterWatch%20Eye%202%20Icon.png</image96x96>
    </icon>
    <android>
        <manifestAdditions><![CDATA[<manifest><uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
		
		
		<uses-permission android:name="android.permission.INTERNET" />
		<uses-permission android:name="android.permission.GET_ACCOUNTS" />
		<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
		<permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" android:protectionLevel="signature" />
		<uses-permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" />
		
		
		<uses-permission android:name="android.permission.WAKE_LOCK" />
		
		
		<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
		<uses-permission android:name="com.android.alarm.permission.SET_ALARM" />
		
		
		<uses-permission android:name="android.permission.VIBRATE" />
		
		<application>
			<activity>
				<intent-filter>
					<action android:name="android.intent.action.MAIN" />
					<category android:name="android.intent.category.LAUNCHER" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.BROWSABLE" />
					<category android:name="android.intent.category.DEFAULT" />
					<data android:scheme="air.com.futurelinesystems.filterwatch" />
				</intent-filter>
			</activity>
		
			
			<receiver android:name="com.doitflash.gcm.handler.GcmBroadcastReceiver.handler.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
				<intent-filter>
					<action android:name="com.google.android.c2dm.intent.RECEIVE" />
					<category android:name="air.com.futurelinesystems.filterwatch" />
				</intent-filter>
			</receiver>
			<service android:name="com.doitflash.gcm.handler.GcmMessageHandler" />
			<receiver android:name="com.doitflash.gcm.alarm.alarmTypes.Alarm_Notification" />
			
			
			<receiver android:name="com.doitflash.gcm.alarm.RebootAutoStartAlarms">
				<intent-filter>
					<action android:name="android.intent.action.BOOT_COMPLETED" />
				</intent-filter>
			</receiver>
			
			
			<activity android:name="com.doitflash.gcm.alarm.WakeActivity" android:theme="@style/Theme.Transparent" />
			
		</application></manifest>]]></manifestAdditions>
    </android>
    <supportedLanguages>en</supportedLanguages>
    <versionLabel>Beta</versionLabel>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.gcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
    </extensions>
</application>`

Thanks in advance

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
