### ISSUE TITLE
GcmMessageHandler crash

### ISSUE THREAD

**Issue by Humi171421** [myflashlab/GCM-ANE#4]
Sometimes the app crash on receiving a message. Many messages arrive without any problem but sometimes the app crashes. It's the same behaivior with or without debug mode. This error only happens on Android devices. I've testet it on three different devies, with the following versions:

* 5.1.1
* 4.4.4
* 5.0.2

I'm using Flex 4.6.0, Air v18

    E/AndroidRuntime(7639): FATAL EXCEPTION: IntentService[GcmMessageHandler]
    E/AndroidRuntime(7639): Process: air.de.betterbits.pushtest, PID: 7639
    E/AndroidRuntime(7639): java.lang.IllegalArgumentException
    E/AndroidRuntime(7639): 	at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
    E/AndroidRuntime(7639): 	at com.doitflash.gcm.handler.GcmMessageHandler.onHandleIntent(GcmMessageHandler.java:58)
    E/AndroidRuntime(7639): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
    E/AndroidRuntime(7639): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime(7639): 	at android.os.Looper.loop(Looper.java:136)
    E/AndroidRuntime(7639): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by myflashlab** [comment]
That's very weird because ```dispatchStatusEventAsync``` should run ONLY when the app is still available and not in the background!

could you please try to upgrade to the latest Air SDK and try again?

**Comment by Humi171421** [comment]
Sorry I didn't mentioned it, this error only occours if the app is still available.
I'm using the latest version of your GCM ANE. And now, I've tried the latest AIR SDK (v20). But the error still occours.

**Comment by Humi171421** [comment]
Are there any new information about this problem, or did you need further informations?

**Comment by myflashlab** [comment]
We were not able to duplicate the problem. will you please be able to say how you are testing this?
