### ISSUE TITLE
Problem after manifest update

### ISSUE THREAD

**Issue by ssteele00** [myflashlab/GCM-ANE#5]
I'm using Flash Builder 4.7 with Apache Flex 15.  After I updated the manifest file, I'm getting the following errors:

Error occurred while packaging the application:

aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
/var/folders/pz/0qhx_w193n128xbz5z3s_9sw0000gp/T/4609a4d8-51a8-43ad-89db-36886d97f016/AndroidManifest.xml:93: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Transparent').

I have narrowed the problem down to this particular addition (as the code compiles fine without it):
					
```
<!-- Required for waking up the device when gcm notification arrives -->
<activity android:name="com.doitflash.gcm.alarm.WakeActivity" android:theme="@style/Theme.Transparent" />
```

Any help would be appreciated.

**Comment by myflashlab** [comment]
Are these video clips helping you? https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by ssteele00** [comment]
No, I have followed the steps but I continue to get the compile error above.

**Comment by myflashlab** [comment]
These compiler error messages means that the ANE is not correctly embedded. First make sure you are using the latest AdobeAir SDK. then make sure you have set the required dependencies to your project?

We have recently updated how the dependencies work. please make sure you are updating them according to the new information here https://github.com/myflashlab/GCM-ANE#requirements

**Comment by ssteele00** [comment]
I have double check everything including the dependencies and I still get the error.  The error only occurs when I try to run the project on an actual Android device.  If I simply build the project, it compiles fine with no errors.

Do you have a sample Flex Builder project you could send me?  That way I could compare that project to my own.

**Comment by ssteele00** [comment]
Finally got it to run with out the manifest error!   I had to remove the extensions from the project and re-add them.  For some reason, Flash Builder was not including them the first time around. 

Thanks.

**Comment by myflashlab** [comment]
Yeah, that happens a lot actually. Although we like Adobe and it's IDE a lot, we love FlashDevelop IDE much more. It's open source **and a lot faster** than FB.
