### ISSUE TITLE
No pop-up items on Notificaiton bar after onMessage event fires

### ISSUE THREAD

**Issue by ssteele00** [myflashlab/GCM-ANE#6]
Ok, I can send a GCM message from PHP just fine... When doing so, I get the following reply from Google:

Google reply: {"multicast_id":6023724769589974278,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1456937742420710%5144637ff9fd7ecd"}]}

In addition, the onMessage event handler fires in the action script and I can see the GCM message payload in a trace  Everything in the payload looks great **however** I never get a new item in the Android Notification Bar.  I've re-check the XML file  but everything looks right there.

Any suggestions on something else I can check?

**Comment by myflashlab** [comment]
On Android, you have the option to turn notification off when the app is running (the default behavior) so you will receive notifications when your app is closed.

**Comment by ssteele00** [comment]
The notification never appears.  I does not matter if the app is open or not.

**Comment by myflashlab** [comment]
You might like to read the discussion here. https://github.com/myflashlab/GCM-ANE/issues/2

**Comment by ssteele00** [comment]
Yeah, I saw that discussion but I wasn't able to find any help there.   Did you get the project files that I emailed?

**Comment by myflashlab** [comment]
My colleagues should get back to you then on your email.

**Comment by ssteele00** [comment]
Okay, I have an update.   
IF the app is completely closed, the notification will appear in the bar and the phone vibrates, BUT
IF the app is open (in either the foreground OR background)......   NO notification.

**Comment by ssteele00** [comment]
If you want the notifications to appear on Android regardless of the apps Open/Closed Foreground/Background state, use:

     _ex.preventDefault = false;

This will force the notification to always appear in the notification bar.
