### ISSUE TITLE
Is there any demo available from where i can test this ane before purchase

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/GCM-ANE#7]
Hello, I am planning to buy this ane but first i want to make sure it works with my game, I have already purchased the faebook ane from here. In your facebook ane you have provided demo version. Is there any demo version where i can test this on my game

**Comment by navdeepyadav** [comment]
Also i have hosted the php demo provided by this zip,  Which seems really hard to send notification from that.

**Comment by myflashlab** [comment]
Of course there is. The demo ANE is available for the GCM like our other ANEs here in GitHub. read the how to here https://github.com/myflashlab/GCM-ANE

The PHP code is showing you the basics of how you can send GCM messages from a server. We don't have a panel for that and instead we are showing you how to do it by directly connecting to Google servers to take care of the messages.
