### ISSUE TITLE
The RegID is always NULL

### ISSUE THREAD

**Issue by mariofaber** [myflashlab/GCM-ANE#8]
Helo!

I am using the ANE and in my tests the RegID always null.

Can you help me?

The setting in the GCM is correct, because I tested with ANE the freshplanet and the register ocurred with sucess.

Thanks.

**Comment by myflashlab** [comment]
If the RegId is null, it means that you have to call the register method of the ANE so it can be generated. And that happens if the settings are ser correctly. Please make sure you have studied the sample project and the manifest settings correctly?

**Comment by myflashlab** [comment]
Please update us on this ticket. If you have a question, please do ask.
