### ISSUE TITLE
I am getting error in publishing it with Myflash lab facebook ane

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/GCM-ANE#9]
![screenshot 2016-03-14 14 14 41](https://cloud.githubusercontent.com/assets/16606299/13739250/18e325a4-e9f0-11e5-8a48-45638158b5d8.png)

Hello, i am create my game with facebook and for handling facebook i am using myflashlab's facebook ane, but I am getting above mentioned error screen while i try to publish this with myflash lab facebook ane.
I am listing here all the ane's that i am using here.
1. commonDependenciesV4.0.ane
2. facebook.ane
3. androidSupport.ane
4. gcm.ane
5. googlePlayServices_gcm.ane

I tried to build it without androidSupport.ane, but still same error appeared there.

**Comment by myflashlab** [comment]
You are over using the dependency ANEs. We have changed how they work and you should use the new versions from now on.

If you are using the GCM and the Facebook ANE together, read the *requirements* section of the ANEs which will tell you which ANEs you should use as the dependencies.

https://github.com/myflashlab/GCM-ANE#requirements  
https://github.com/myflashlab/facebook-ANE#requirements

**commonDependenciesVx.x.ane** is depricated

**Comment by navdeepyadav** [comment]
Thanks, This was helpful and now i am able to build the apk
